apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: storage-database-0
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  volumeName: pvc-ade968d5-c199-4f2f-999f-a4d540d9d73e
