apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-myapp  ## .Release references chart.yaml
spec:
  replicas: {{ .Values.replicas }}  ## .Values references values.yaml
  selector:
    matchLabels:
      app: myapp
  template:
    metadata:
      labels:
        app: myapp
    spec:
      containers:
        - name: myapp
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          ports:
            - containerPort: 80
