apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-svc  ## .Release references chart.yaml
spec:
  selector:
    app: myapp
  ports:
    - port: {{ .Values.service.port }}  ## .Values references values.yaml
      targetPort: 80
