apiVersion: v1
kind: PersistentVolume
metadata:
  name: postgres-pv
  labels:
    disk: postgres-storage
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  storageClassName: manual
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: /data/postgres
